name: image_picker
description: Flutter plugin for selecting images from the Android and iOS image
  library, and taking new pictures with the camera.
homepage: https://github.com/flutter/plugins/tree/master/packages/image_picker/image_picker
version: 0.6.7+22

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.imagepicker
        pluginClass: ImagePickerPlugin
      ios:
        pluginClass: FLTImagePickerPlugin

dependencies:
  flutter:
    sdk: flutter
  flutter_plugin_android_lifecycle: ^2.0.5
  image_picker_platform_interface: ^2.4.3

dev_dependencies:
  video_player: ^2.2.16
  flutter_test:
    sdk: flutter
  integration_test:
    path: ../../integration_test
  mockito: ^5.0.17
  pedantic: ^1.11.1
  plugin_platform_interface: ^2.1.2

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.10.0"
